// Didit Wallet login
const AUTH_WALLET_AUTHORIZATION_PATH = '/wallet-authorization';
const AUTH_TOKEN_PATH = '/token';

// Email auth login
const EMAIL_AUTH_DEFAULT_BASE_URL = 'https://apx.dev.didit.me/email-auth';
const EMAIL_AUTH_AUTHORIZATION_PATH = '/oidc/authorize/';
const EMAIL_AUTH_REDIRECT_URI_PATH = '/oidc/callback/';
const EMAIL_AUTH_CODE_CHALLENGE_METHOD = 'S256';
const EMAIL_AUTH_RESPONSE_TYPE = 'code';
const EMAIL_AUTH_SCOPE = 'openid';
const EMAIL_AUTH_CODE_VERIFIER_NAME = 'didit_auth_code_verifier';
const EMAIL_AUTH_INIT_POST_MESSAGE_TYPE = 'didit-auth-init';
const EMAIL_AUTH_TOKEN_POST_MESSAGE_TYPE = 'didit-auth-token';
const EMAIL_AUTH_TOKEN_POST_MESSAGE_ERROR_TYPE = 'didit-auth-token-error';
const EMAIL_AUTH_POPUP_WIDTH = 400;
const EMAIL_AUTH_POPUP_HEIGHT = 600;

// General Didit
const TOKEN_COOKIE_NAME = 'didit_token';
const WALLET_ADDRESS_COOKIE_NAME = 'didit_wallet_address';

const DIDIT = {
  AUTH_TOKEN_PATH,
  AUTH_WALLET_AUTHORIZATION_PATH,
  EMAIL_AUTH_AUTHORIZATION_PATH,
  EMAIL_AUTH_CODE_CHALLENGE_METHOD,
  EMAIL_AUTH_CODE_VERIFIER_NAME,
  EMAIL_AUTH_DEFAULT_BASE_URL,
  EMAIL_AUTH_INIT_POST_MESSAGE_TYPE,
  EMAIL_AUTH_POPUP_HEIGHT,
  EMAIL_AUTH_POPUP_WIDTH,
  EMAIL_AUTH_REDIRECT_URI_PATH,
  EMAIL_AUTH_RESPONSE_TYPE,
  EMAIL_AUTH_SCOPE,
  EMAIL_AUTH_TOKEN_POST_MESSAGE_ERROR_TYPE,
  EMAIL_AUTH_TOKEN_POST_MESSAGE_TYPE,
  TOKEN_COOKIE_NAME,
  WALLET_ADDRESS_COOKIE_NAME,
};

export { DIDIT };
